# 配置 AppVeyor 版本
version: 1.0.{build}

# 定义要运行的环境
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204

# 构建脚本
build_script:
  # Windows 环境下的 CMake 构建
  - ps: |
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2022") {
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
      }

  # Ubuntu 环境下的 CMake 构建
  - sh: |
      if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu2204" ]; then
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
      fi
