{
 "title": "mqtt-server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "mqtt活跃连接总数",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mqtt_active_connections)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mqtt服务端活跃连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mqtt_active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mqtt客户端主题订阅总速率（msg/s）",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqtt_sub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mqtt客户端主题订阅速率 (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client_id) (rate(mqtt_sub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mqtt客户端主题发布总速率（msg/s）",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mqtt_pub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mqtt客户端主题发布速率 (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (client_id) (rate(mqtt_pub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mqtt客户端主题发布速率-Qos维度 (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (quality) (rate(mqtt_pub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mqtt客户端主题订阅速率-Qos维度 (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (quality) (rate(mqtt_sub_topic_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}